name: V2Ray Config Collector

on:
  schedule:
    - cron: '0 */1 * * *' # هر یک ساعت اجرا می‌شود
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه پوش کردن به اکشن
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Collector Script
        run: python collector.py # اسکریپت پایتون اجرا می‌شود و همه‌ی فایل‌ها را می‌سازد

      - name: List files in directory
        run: ls -la # برای دیباگ، لیست فایل‌ها رو نشون می‌ده

      - name: Commit and Push new sub files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          
          # --- تغییر اصلی اینجاست ---
          # به جای اسم فایل خاص، همه تغییرات رو اضافه می‌کنه
          git add .
          
          # --- این هم برای دیباگ اضافه شد ---
          # به ما نشون می‌ده چه فایل‌هایی استیج شدن
          git status
          
          # چک می‌کند که آیا تغییری برای کامیت وجود دارد یا نه
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            echo "Changes detected, committing and pushing..."
            git commit -m "Updated subscription files (all files)"
            git push
          fi


